theme: hugo-PaperMod
title: withonlyamap
baseURL: "https://withonlyamap.com/"
copyright: "2014-{year}. All designs and content by John Nutter"
enableEmoji: true
languageCode: en-us
staticDir: static

menu:
  main:
    - identifier: Home
      name: Home
      url: /
      weight: 10
    - identifier: About
      name: About
      url: /about
      weight: 20
    - identifier: Projects
      name: Projects
      url: /projects
      weight: 30

params:
  defaultTheme: light
  disableThemeToggle: true
  homeInfoParams: 
    Content: "A personal outlet for writing about music, art, science and life in general. "
    Title: "Explorations in music"
  socialIcons: 
    - 
      name: instagram
      url: "https://www.instagram.com/withonlyamap/"
    - 
      name: twitter
      url: "https://twitter.com/withonlyamap"
    -
      name: bandcamp
      url: "https://bandcamp.com/withonlyamap"
